language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=21.1.2
android:
  components:
    - tools
    - platform-tools
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
before_script:
  - echo no | android create avd --force -n test -t "android-21" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
jobs:
  include:
    - stage: test
      script:
        - ./gradlew test
    - stage: androidTest
      script:
        - ./gradlew connectedCheck
        - ./gradlew build jacocoTestReport
after_success:
  — bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - tiagocasemiro@hotmail.com
      - tiagopaivacasemiro@gmail.com
    on_success: never
    on_failure: always