language: android
install: true
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=21.1.2
android:
  components:
    - tools
    - platform-tools
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
before_install:
  - chmod +x gradlew
  - pip install
before_script:
  - echo no | android create avd --force -n test -t "android-21" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window -no-boot-anim &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
script:
  - ./gradlew connectedCheck
  - ./gradlew build jacocoTestReport
after_success:
  — bash <(curl -s https://codecov.io/bash)
  - codecov
notifications:
  email:
    recipients:
      - tiagocasemiro@hotmail.com
      - tiagopaivacasemiro@gmail.com
    on_success: never
    on_failure: always
