language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version
    - build-tools-26.0.2

    # The SDK version
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Least system image
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
script:
  - ./gradlew test
  - ./gradlew connectedCheck
  — ./gradlew build jacocoTestReport
after_success:
  — bash <(curl -s https://codecov.io/bash)